<a href="https://colab.research.google.com/github/avikalsagar/Predicting_Annual_Variability_Renewable_Energy/blob/main/Avg_SPP_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pytz

In [2]:
df = pd.read_csv("merged_dataset_SPP.csv")

In [3]:
df

,Unnamed: 0,GMT MKT Interval,Coal Market,Coal Self,Diesel Fuel Oil Market,Diesel Fuel Oil Self,Hydro Market,Hydro Self,Natural Gas Market,Gas Self,...,Solar Self,Waste Disposal Services Market,Waste Disposal Services Self,Wind Market,Wind Self,Waste Heat Market,Waste Heat Self,Other Market,Other Self,Load
0,0,2018-01-01T06:00:00Z,2948.5,18203.9,0.0,4.4,43.1,759.6,5903.9,3447.6,...,0.0,0.0,10.8,0.0,3643.1,0.0,0.0,0.0,27.1,36439.754
1,1,2018-01-01T06:05:00Z,2917.3,18191.4,0.0,4.4,43.3,775.3,5842.2,3468.0,...,0.0,0.0,10.9,0.0,3619.8,0.0,0.0,0.0,27.3,36389.511
2,2,2018-01-01T06:10:00Z,2916.5,18181.4,0.0,0.0,43.8,802.2,5983.2,3479.6,...,0.0,0.0,11.0,0.0,3578.9,0.0,0.0,0.0,27.0,36386.829
3,3,2018-01-01T06:15:00Z,2913.0,18159.0,0.0,0.0,43.8,776.5,6116.0,3385.1,...,0.0,0.0,10.9,0.0,3539.2,0.0,0.0,0.0,26.9,36290.426
4,4,2018-01-01T06:20:00Z,2911.5,18154.1,0.0,0.0,43.3,713.7,6182.6,3438.3,...,0.0,0.0,10.9,0.0,3515.1,0.0,0.0,0.0,27.3,36225.646
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525638,525638,2023-01-01T05:40:00Z,4112.9,4025.6,0.0,0.0,18.3,375.8,4552.8,403.5,...,0.9,1.0,10.8,0.0,11580.6,0.0,0.0,0.0,18.4,26601.346
525639,525639,2023-01-01T05:45:00Z,4133.9,4048.3,0.0,0.0,18.4,376.6,4583.7,399.5,...,0.8,1.0,10.8,0.0,11492.8,0.0,0.0,0.0,18.0,26584.786
525640,525640,2023-01-01T05:50:00Z,4144.8,4040.8,0.0,0.0,18.2,376.2,4573.5,399.4,...,0.7,1.0,10.6,0.0,11440.0,0.0,0.0,0.0,17.9,26508.336
525641,525641,2023-01-01T05:55:00Z,4134.9,4018.6,0.0,0.0,18.3,376.2,4523.1,413.5,...,0.9,1.0,10.6,0.0,11429.4,0.0,0.0,0.0,18.3,26509.875
525642,525642,2023-01-01T06:00:00Z,4335.6,3876.6,0.0,0.0,18.3,376.2,4461.8,589.1,...,0.6,1.0,10.7,0.0,11315.9,0.0,0.0,0.0,20.6,26486.917

In [4]:
# Renaming the first column (taken directly from thr GitHub code)
df.rename({'GMT MKT Interval': "DatetimeGMT"}, axis=1, inplace=True)
# Converting this column into Pandas datetime
df['DatetimeGMT'] = pd.to_datetime(df['DatetimeGMT'])

In [5]:
# Performing the merge as explained in previous code cell
df['Coal'] = df[' Coal Market'] + df[' Coal Self']
df.drop([' Coal Market', ' Coal Self'], axis=1, inplace=True)

df['Diesel'] = df[' Diesel Fuel Oil Market'] + df[' Diesel Fuel Oil Self']
df.drop([' Diesel Fuel Oil Market', ' Diesel Fuel Oil Self'], axis=1, inplace=True)

df['Hydro'] = df[' Hydro Market'] + df[' Hydro Self']
df.drop([' Hydro Market', ' Hydro Self'], axis=1, inplace=True)

df['Gas'] = df[' Natural Gas Market'] + df[' Gas Self']
df.drop([' Natural Gas Market', ' Gas Self'], axis=1, inplace=True)

df['Nuclear'] = df[' Nuclear Market'] + df[' Nuclear Self']
df.drop([' Nuclear Market', ' Nuclear Self'], axis=1, inplace=True)

df['Solar'] = df[' Solar Market'] + df[' Solar Self']
df.drop([' Solar Market', ' Solar Self'], axis=1, inplace=True)

df['Waste'] = df[' Waste Disposal Services Market'] + df[' Waste Disposal Services Self']
df.drop([' Waste Disposal Services Market', ' Waste Disposal Services Self'], axis=1, inplace=True)

df['Wind'] = df[' Wind Market'] + df[' Wind Self']
df.drop([' Wind Market', ' Wind Self'], axis=1, inplace=True)

df['Waste heat'] = df[' Waste Heat Market'] + df[' Waste Heat Self']
df.drop([' Waste Heat Market', ' Waste Heat Self'], axis=1, inplace=True)

df['Other'] = df[' Other Market'] + df[' Other Self']
df.drop([' Other Market', ' Other Self'], axis=1, inplace=True)

In [6]:
df['DatetimeGMT'] = df['DatetimeGMT'].dt.tz_convert(pytz.timezone('US/Eastern'))
df['Date'] = df['DatetimeGMT'].dt.strftime('%Y-%m-%d %H:%M:%S')
df

,Unnamed: 0,DatetimeGMT,Load,Coal,Diesel,Hydro,Gas,Nuclear,Solar,Waste,Wind,Waste heat,Other,Date
0,0,2018-01-01 01:00:00-05:00,36439.754,21152.4,4.4,802.7,9351.5,2033.8,0.0,10.8,3643.1,0.0,27.1,2018-01-01 01:00:00
1,1,2018-01-01 01:05:00-05:00,36389.511,21108.7,4.4,818.6,9310.2,2034.4,0.0,10.9,3619.8,0.0,27.3,2018-01-01 01:05:00
2,2,2018-01-01 01:10:00-05:00,36386.829,21097.9,0.0,846.0,9462.8,2034.0,0.0,11.0,3578.9,0.0,27.0,2018-01-01 01:10:00
3,3,2018-01-01 01:15:00-05:00,36290.426,21072.0,0.0,820.3,9501.1,2034.4,0.0,10.9,3539.2,0.0,26.9,2018-01-01 01:15:00
4,4,2018-01-01 01:20:00-05:00,36225.646,21065.6,0.0,757.0,9620.9,2034.5,0.0,10.9,3515.1,0.0,27.3,2018-01-01 01:20:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525638,525638,2023-01-01 00:40:00-05:00,26601.346,8138.5,0.0,394.1,4956.3,2041.8,0.9,11.8,11580.6,0.0,18.4,2023-01-01 00:40:00
525639,525639,2023-01-01 00:45:00-05:00,26584.786,8182.2,0.0,395.0,4983.2,2042.2,0.8,11.8,11492.8,0.0,18.0,2023-01-01 00:45:00
525640,525640,2023-01-01 00:50:00-05:00,26508.336,8185.6,0.0,394.4,4972.9,2039.7,0.7,11.6,11440.0,0.0,17.9,2023-01-01 00:50:00
525641,525641,2023-01-01 00:55:00-05:00,26509.875,8153.5,0.0,394.5,4936.6,2040.3,0.9,11.6,11429.4,0.0,18.3,2023-01-01 00:55:00
525642,525642,2023-01-01 01:00:00-05:00,26486.917,8212.2,0.0,394.5,5050.9,2038.7,0.6,11.7,11315.9,0.0,20.6,2023-01-01 01:00:00

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525643 entries, 0 to 525642
Data columns (total 14 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Unnamed: 0   525643 non-null  int64
 1   DatetimeGMT  525643 non-null  datetime64[ns, US/Eastern]
 2    Load        523859 non-null  float64
 3   Coal         523859 non-null  float64
 4   Diesel       523859 non-null  float64
 5   Hydro        523859 non-null  float64
 6   Gas          523859 non-null  float64
 7   Nuclear      523859 non-null  float64
 8   Solar        523859 non-null  float64
 9   Waste        523859 non-null  float64
 10  Wind         523859 non-null  float64
 11  Waste heat   523859 non-null  float64
 12  Other        523859 non-null  float64
 13  Date         525643 non-null  object
dtypes: datetime64[ns, US/Eastern](1), float64(11), int64(1), object(1)
memory usage: 56.1+ MB

In [8]:
df.drop('DatetimeGMT', axis = 1, inplace = True)
df['Date'] = pd.to_datetime(df['Date'])
df.set_index('Date', inplace=True)
df = df.sort_index()
df = df[~df.index.duplicated(keep='first')]
df

,Unnamed: 0,Load,Coal,Diesel,Hydro,Gas,Nuclear,Solar,Waste,Wind,Waste heat,Other
Date,,,,,,,,,,,,
2018-01-01 01:00:00,0,36439.754,21152.4,4.4,802.7,9351.5,2033.8,0.0,10.8,3643.1,0.0,27.1
2018-01-01 01:05:00,1,36389.511,21108.7,4.4,818.6,9310.2,2034.4,0.0,10.9,3619.8,0.0,27.3
2018-01-01 01:10:00,2,36386.829,21097.9,0.0,846.0,9462.8,2034.0,0.0,11.0,3578.9,0.0,27.0
2018-01-01 01:15:00,3,36290.426,21072.0,0.0,820.3,9501.1,2034.4,0.0,10.9,3539.2,0.0,26.9
2018-01-01 01:20:00,4,36225.646,21065.6,0.0,757.0,9620.9,2034.5,0.0,10.9,3515.1,0.0,27.3
...,...,...,...,...,...,...,...,...,...,...,...,...
2023-01-01 00:40:00,525638,26601.346,8138.5,0.0,394.1,4956.3,2041.8,0.9,11.8,11580.6,0.0,18.4
2023-01-01 00:45:00,525639,26584.786,8182.2,0.0,395.0,4983.2,2042.2,0.8,11.8,11492.8,0.0,18.0
2023-01-01 00:50:00,525640,26508.336,8185.6,0.0,394.4,4972.9,2039.7,0.7,11.6,11440.0,0.0,17.9
2023-01-01 00:55:00,525641,26509.875,8153.5,0.0,394.5,4936.6,2040.3,0.9,11.6,11429.4,0.0,18.3
2023-01-01 01:00:00,525642,26486.917,8212.2,0.0,394.5,5050.9,2038.7,0.6,11.7,11315.9,0.0,20.6

In [9]:
df['Hour'] = df.index.hour
df

,Unnamed: 0,Load,Coal,Diesel,Hydro,Gas,Nuclear,Solar,Waste,Wind,Waste heat,Other,Hour
Date,,,,,,,,,,,,,
2018-01-01 01:00:00,0,36439.754,21152.4,4.4,802.7,9351.5,2033.8,0.0,10.8,3643.1,0.0,27.1,1
2018-01-01 01:05:00,1,36389.511,21108.7,4.4,818.6,9310.2,2034.4,0.0,10.9,3619.8,0.0,27.3,1
2018-01-01 01:10:00,2,36386.829,21097.9,0.0,846.0,9462.8,2034.0,0.0,11.0,3578.9,0.0,27.0,1
2018-01-01 01:15:00,3,36290.426,21072.0,0.0,820.3,9501.1,2034.4,0.0,10.9,3539.2,0.0,26.9,1
2018-01-01 01:20:00,4,36225.646,21065.6,0.0,757.0,9620.9,2034.5,0.0,10.9,3515.1,0.0,27.3,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-01-01 00:40:00,525638,26601.346,8138.5,0.0,394.1,4956.3,2041.8,0.9,11.8,11580.6,0.0,18.4,0
2023-01-01 00:45:00,525639,26584.786,8182.2,0.0,395.0,4983.2,2042.2,0.8,11.8,11492.8,0.0,18.0,0
2023-01-01 00:50:00,525640,26508.336,8185.6,0.0,394.4,4972.9,2039.7,0.7,11.6,11440.0,0.0,17.9,0
2023-01-01 00:55:00,525641,26509.875,8153.5,0.0,394.5,4936.6,2040.3,0.9,11.6,11429.4,0.0,18.3,0
2023-01-01 01:00:00,525642,26486.917,8212.2,0.0,394.5,5050.9,2038.7,0.6,11.7,11315.9,0.0,20.6,1

In [10]:
hourly_mean_load = df.groupby([df.index.date, 'Hour']).agg({' Load': 'sum', **{col: 'sum' for col in df.columns if (col != ' Load' and col != 'Hour')}})
hourly_mean_load

                       Load  Unnamed: 0      Coal  Diesel    Hydro       Gas  \
           Hour
2018-01-01 1     435175.406          66  252979.6     8.8   8437.6  115428.1
           2     433136.664         210  254174.5     0.0   6373.6  109497.4
           3     432544.152         354  254355.6     0.0   6355.1  111666.6
           4     432570.416         498  255091.5     0.0   6351.8  109633.5
           5     436211.546         642  253726.0     0.0   6511.0  119693.8
...                     ...         ...       ...     ...      ...       ...
2022-12-31 21    335981.554     6307194  111101.9     0.0  10095.5   71008.8
           22    331758.199     6307338  101132.1     0.0   9732.2   63777.6
           23    325701.211     6307482  100272.8     0.0   5194.9   62128.2
2023-01-01 0     319850.526     6307626   98251.3     0.0   4736.1   59553.1
           1      26486.917      525642    8212.2     0.0    394.5    5050.9

                 Nuclear  Solar  Waste      Wind  Waste heat  Other
           Hour
2018-01-01 1     24410.6    0.0  130.8   41819.9         0.0  326.9
           2     24414.7    1.4  130.3   38397.5         0.0  326.2
           3     24408.1   14.2  131.1   38098.6         0.0  325.1
           4     24413.0   54.7  131.9   37790.8         0.0  327.5
           5     24413.1   91.1  131.0   35006.1         0.0  326.5
...                  ...    ...    ...       ...         ...    ...
2022-12-31 21    24490.1    8.7  129.9  130218.4         0.0  218.8
           22    24482.9    9.2  129.9  138285.2         0.0  219.2
           23    24484.2   10.1  140.5  137609.9         0.0  218.4
2023-01-01 0     24487.4   10.0  140.4  138478.4         0.0  217.5
           1      2038.7    0.6   11.7   11315.9         0.0   20.6

[43815 rows x 12 columns]

In [11]:
indices = hourly_mean_load.index
indices

MultiIndex([(2018-01-01,  1),
            (2018-01-01,  2),
            (2018-01-01,  3),
            (2018-01-01,  4),
            (2018-01-01,  5),
            (2018-01-01,  6),
            (2018-01-01,  7),
            (2018-01-01,  8),
            (2018-01-01,  9),
            (2018-01-01, 10),
            ...
            (2022-12-31, 16),
            (2022-12-31, 17),
            (2022-12-31, 18),
            (2022-12-31, 19),
            (2022-12-31, 20),
            (2022-12-31, 21),
            (2022-12-31, 22),
            (2022-12-31, 23),
            (2023-01-01,  0),
            (2023-01-01,  1)],
           names=[None, 'Hour'], length=43815)

In [14]:
final_data = pd.DataFrame(hourly_mean_load, index = indices)
final_data = final_data.reset_index()
final_data['Date'] = pd.to_datetime(final_data['level_0'])
final_data

,level_0,Hour,Load,Unnamed: 0,Coal,Diesel,Hydro,Gas,Nuclear,Solar,Waste,Wind,Waste heat,Other,Date
0,2018-01-01,1,435175.406,66,252979.6,8.8,8437.6,115428.1,24410.6,0.0,130.8,41819.9,0.0,326.9,2018-01-01
1,2018-01-01,2,433136.664,210,254174.5,0.0,6373.6,109497.4,24414.7,1.4,130.3,38397.5,0.0,326.2,2018-01-01
2,2018-01-01,3,432544.152,354,254355.6,0.0,6355.1,111666.6,24408.1,14.2,131.1,38098.6,0.0,325.1,2018-01-01
3,2018-01-01,4,432570.416,498,255091.5,0.0,6351.8,109633.5,24413.0,54.7,131.9,37790.8,0.0,327.5,2018-01-01
4,2018-01-01,5,436211.546,642,253726.0,0.0,6511.0,119693.8,24413.1,91.1,131.0,35006.1,0.0,326.5,2018-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
43810,2022-12-31,21,335981.554,6307194,111101.9,0.0,10095.5,71008.8,24490.1,8.7,129.9,130218.4,0.0,218.8,2022-12-31
43811,2022-12-31,22,331758.199,6307338,101132.1,0.0,9732.2,63777.6,24482.9,9.2,129.9,138285.2,0.0,219.2,2022-12-31
43812,2022-12-31,23,325701.211,6307482,100272.8,0.0,5194.9,62128.2,24484.2,10.1,140.5,137609.9,0.0,218.4,2022-12-31
43813,2023-01-01,0,319850.526,6307626,98251.3,0.0,4736.1,59553.1,24487.4,10.0,140.4,138478.4,0.0,217.5,2023-01-01
43814,2023-01-01,1,26486.917,525642,8212.2,0.0,394.5,5050.9,2038.7,0.6,11.7,11315.9,0.0,20.6,2023-01-01

In [16]:
final_data.to_csv("Avg SPP (2018-22).csv")