<a href="https://colab.research.google.com/github/avikalsagar/Predicting_Annual_Variability_Renewable_Energy/blob/main/Merging_SPP_datasets_(18_22).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import requests
import matplotlib.pyplot as plt
import numpy
import pytz
from matplotlib.ticker import MaxNLocator

------

In [12]:
data_18 = pd.read_csv("GenMix_2018.csv")
data_19 = pd.read_csv("GenMix_2019.csv")
data_20 = pd.read_csv("GenMix_2020.csv")
data_21 = pd.read_csv("GenMix_2021.csv")
data_22 = pd.read_csv("GenMix_2022.csv")

In [13]:
data = [data_18, data_19, data_20, data_21, data_22]
for data in data:
  print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104874 entries, 0 to 104873
Data columns (total 22 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   GMT MKT Interval                 104874 non-null  object
 1    Coal Market                     104874 non-null  float64
 2    Coal Self                       104874 non-null  float64
 3    Diesel Fuel Oil Market          104874 non-null  float64
 4    Diesel Fuel Oil Self            104874 non-null  float64
 5    Hydro Market                    104874 non-null  float64
 6    Hydro Self                      104874 non-null  float64
 7    Natural Gas Market              104874 non-null  float64
 8    Gas Self                        104874 non-null  float64
 9    Nuclear Market                  104874 non-null  int64
 10   Nuclear Self                    104874 non-null  float64
 11   Solar Market                    104874 non-null  int64
 12   Solar Self                      104874 non-null  float64
 13   Waste Disposal Services Market  104874 non-null  int64
 14   Waste Disposal Services Self    104874 non-null  float64
 15   Wind Market                     104874 non-null  int64
 16   Wind Self                       104874 non-null  float64
 17   Waste Heat Market               104874 non-null  int64
 18   Waste Heat Self                 104874 non-null  int64
 19   Other Market                    104874 non-null  float64
 20   Other Self                      104874 non-null  float64
 21   Load                            104874 non-null  float64
dtypes: float64(15), int64(6), object(1)
memory usage: 17.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105120 entries, 0 to 105119
Data columns (total 22 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   GMT MKT Interval                 105120 non-null  object
 1    Coal Market                     104758 non-null  float64
 2    Coal Self                       104758 non-null  float64
 3    Diesel Fuel Oil Market          104758 non-null  float64
 4    Diesel Fuel Oil Self            104758 non-null  float64
 5    Hydro Market                    104758 non-null  float64
 6    Hydro Self                      104758 non-null  float64
 7    Natural Gas Market              104758 non-null  float64
 8    Gas Self                        104758 non-null  float64
 9    Nuclear Market                  104758 non-null  float64
 10   Nuclear Self                    104758 non-null  float64
 11   Solar Market                    104758 non-null  float64
 12   Solar Self                      104758 non-null  float64
 13   Waste Disposal Services Market  104758 non-null  float64
 14   Waste Disposal Services Self    104758 non-null  float64
 15   Wind Market                     104758 non-null  float64
 16   Wind Self                       104758 non-null  float64
 17   Waste Heat Market               104758 non-null  float64
 18   Waste Heat Self                 104758 non-null  float64
 19   Other Market                    104758 non-null  float64
 20   Other Self                      104758 non-null  float64
 21   Load                            104758 non-null  float64
dtypes: float64(21), object(1)
memory usage: 17.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105408 entries, 0 to 105407
Data columns (total 22 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   GMT MKT Interval                 105408 non-null  object
 1    Coal Market                     105121 non-null  float64
 2    Coal Self                       105121 non-null  float64
 3    Diesel Fuel Oil Market          105121 non-null  float64
 4    Diesel Fuel Oil Self            105121 non-null  float64
 5    Hydro Market                    105121 non-null  float64
 6    Hydro Self                      105121 non-null  float64
 7    Natural Gas Market              105121 non-null  float64
 8    Gas Self                        105121 non-null  float64
 9    Nuclear Market                  105121 non-null  float64
 10   Nuclear Self                    105121 non-null  float64
 11   Solar Market                    105121 non-null  float64
 12   Solar Self                      105121 non-null  float64
 13   Waste Disposal Services Market  105121 non-null  float64
 14   Waste Disposal Services Self    105121 non-null  float64
 15   Wind Market                     105121 non-null  float64
 16   Wind Self                       105121 non-null  float64
 17   Waste Heat Market               105121 non-null  float64
 18   Waste Heat Self                 105121 non-null  float64
 19   Other Market                    105121 non-null  float64
 20   Other Self                      105121 non-null  float64
 21   Load                            105121 non-null  float64
dtypes: float64(21), object(1)
memory usage: 17.7+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105121 entries, 0 to 105120
Data columns (total 22 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   GMT MKT Interval                 105121 non-null  object
 1    Coal Market                     104817 non-null  float64
 2    Coal Self                       104817 non-null  float64
 3    Diesel Fuel Oil Market          104817 non-null  float64
 4    Diesel Fuel Oil Self            104817 non-null  float64
 5    Hydro Market                    104817 non-null  float64
 6    Hydro Self                      104817 non-null  float64
 7    Natural Gas Market              104817 non-null  float64
 8    Gas Self                        104817 non-null  float64
 9    Nuclear Market                  104817 non-null  float64
 10   Nuclear Self                    104817 non-null  float64
 11   Solar Market                    104817 non-null  float64
 12   Solar Self                      104817 non-null  float64
 13   Waste Disposal Services Market  104817 non-null  float64
 14   Waste Disposal Services Self    104817 non-null  float64
 15   Wind Market                     104817 non-null  float64
 16   Wind Self                       104817 non-null  float64
 17   Waste Heat Market               104817 non-null  float64
 18   Waste Heat Self                 104817 non-null  float64
 19   Other Market                    104817 non-null  float64
 20   Other Self                      104817 non-null  float64
 21   Load                            104817 non-null  float64
dtypes: float64(21), object(1)
memory usage: 17.6+ MB
None
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105120 entries, 0 to 105119
Data columns (total 22 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   GMT MKT Interval                 105120 non-null  object
 1    Coal Market                     104289 non-null  float64
 2    Coal Self                       104289 non-null  float64
 3    Diesel Fuel Oil Market          104289 non-null  float64
 4    Diesel Fuel Oil Self            104289 non-null  float64
 5    Hydro Market                    104289 non-null  float64
 6    Hydro Self                      104289 non-null  float64
 7    Natural Gas Market              104289 non-null  float64
 8    Gas Self                        104289 non-null  float64
 9    Nuclear Market                  104289 non-null  float64
 10   Nuclear Self                    104289 non-null  float64
 11   Solar Market                    104289 non-null  float64
 12   Solar Self                      104289 non-null  float64
 13   Waste Disposal Services Market  104289 non-null  float64
 14   Waste Disposal Services Self    104289 non-null  float64
 15   Wind Market                     104289 non-null  float64
 16   Wind Self                       104289 non-null  float64
 17   Waste Heat Market               104289 non-null  float64
 18   Waste Heat Self                 104289 non-null  float64
 19   Other Market                    104289 non-null  float64
 20   Other Self                      104289 non-null  float64
 21   Load                            104289 non-null  float64
dtypes: float64(21), object(1)
memory usage: 17.6+ MB
None

In [14]:
data = pd.concat([data_18, data_19, data_20, data_21, data_22], ignore_index=True)
data

,GMT MKT Interval,Coal Market,Coal Self,Diesel Fuel Oil Market,Diesel Fuel Oil Self,Hydro Market,Hydro Self,Natural Gas Market,Gas Self,Nuclear Market,...,Solar Self,Waste Disposal Services Market,Waste Disposal Services Self,Wind Market,Wind Self,Waste Heat Market,Waste Heat Self,Other Market,Other Self,Load
0,2018-01-01T06:00:00Z,2948.5,18203.9,0.0,4.4,43.1,759.6,5903.9,3447.6,0.0,...,0.0,0.0,10.8,0.0,3643.1,0.0,0.0,0.0,27.1,36439.754
1,2018-01-01T06:05:00Z,2917.3,18191.4,0.0,4.4,43.3,775.3,5842.2,3468.0,0.0,...,0.0,0.0,10.9,0.0,3619.8,0.0,0.0,0.0,27.3,36389.511
2,2018-01-01T06:10:00Z,2916.5,18181.4,0.0,0.0,43.8,802.2,5983.2,3479.6,0.0,...,0.0,0.0,11.0,0.0,3578.9,0.0,0.0,0.0,27.0,36386.829
3,2018-01-01T06:15:00Z,2913.0,18159.0,0.0,0.0,43.8,776.5,6116.0,3385.1,0.0,...,0.0,0.0,10.9,0.0,3539.2,0.0,0.0,0.0,26.9,36290.426
4,2018-01-01T06:20:00Z,2911.5,18154.1,0.0,0.0,43.3,713.7,6182.6,3438.3,0.0,...,0.0,0.0,10.9,0.0,3515.1,0.0,0.0,0.0,27.3,36225.646
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
525638,2023-01-01T05:40:00Z,4112.9,4025.6,0.0,0.0,18.3,375.8,4552.8,403.5,0.0,...,0.9,1.0,10.8,0.0,11580.6,0.0,0.0,0.0,18.4,26601.346
525639,2023-01-01T05:45:00Z,4133.9,4048.3,0.0,0.0,18.4,376.6,4583.7,399.5,0.0,...,0.8,1.0,10.8,0.0,11492.8,0.0,0.0,0.0,18.0,26584.786
525640,2023-01-01T05:50:00Z,4144.8,4040.8,0.0,0.0,18.2,376.2,4573.5,399.4,0.0,...,0.7,1.0,10.6,0.0,11440.0,0.0,0.0,0.0,17.9,26508.336
525641,2023-01-01T05:55:00Z,4134.9,4018.6,0.0,0.0,18.3,376.2,4523.1,413.5,0.0,...,0.9,1.0,10.6,0.0,11429.4,0.0,0.0,0.0,18.3,26509.875
525642,2023-01-01T06:00:00Z,4335.6,3876.6,0.0,0.0,18.3,376.2,4461.8,589.1,0.0,...,0.6,1.0,10.7,0.0,11315.9,0.0,0.0,0.0,20.6,26486.917